services:
  ProjectZomboidDedicatedServerArm64:
    image: zomboid-server-arm64:latest
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "16261:16261/udp"
      - "16262:16262/udp"
      - "8766:8766/udp"
      - "8767:8767/udp"
      - "16262-16272:16262-16272/tcp"
      - "27015:27015/tcp"
    volumes:
      # Server data
      - ./data:/home/steam/Zomboid
      # Server files (persisted on host)
      - ./server-files:/home/steam/pz-dedicated
      # Workshop mods folder
      - ./workshop-mods:/home/steam/pz-dedicated/steamapps/workshop
